services:
  mysql:
    image: mysql:8.0
    container_name: stockflow-kelompok-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: inventory
      MYSQL_USER: invuser
      MYSQL_PASSWORD: invpass123
    ports:
      - "3309:3306"
    volumes:
      - inv_mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass123"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: stockflow-kelompok-api
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: base64:EpYtTQ6d4brrDtm9aFXsYFQvBUsbizt+MhklWfJ6m6c=
      APP_URL: http://localhost:3000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_DATABASE: inventory
      DB_USERNAME: invuser
      DB_PASSWORD: invpass123
      SANCTUM_STATEFUL_DOMAINS: localhost:3000
      SESSION_DOMAIN: localhost
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: stockflow-kelompok-nginx
    ports:
      - "8006:80"
    depends_on:
      - api
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: stockflow-kelompok-frontend
    ports:
      - "3001:80"
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  inv_mysqldata:
